sudo: required
services:
  - docker

script:
  - docker build -t $DOCKER_ID/puppeteer-api:latest -f ./Dockerfile ./
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/puppeteer-api:latest